### PR TITLE
adding aqara button support

### PR DESCRIPTION
**Pull request by bspranger**
first attempt at a hubitat Device Driver.

### CODE REVIEW

**Comment by bspranger** [comment]
updated the code to support release, single, double, triple and quadruple presses.

**Comment by bspranger** [comment]
I like how this button works now.  There is only one event for a push & release.  I simulate the release in two ways.  Momentary mode runs a function in a setable number of seconds, and then sets button 0 for release.  Toggle will switch between button 0 and button 1 being pressed simulating On/Off.

**Comment by veeceeoh** [comment]
Looks good to me! The use of button 0 is interesting, though I will have to do some testing with my "original" Xioami button driver to see if button 0 can be used by Hubitat's apps (Rule Machine, Button Controller, etc.) Otherwise it will be useful for people using WebCoRE ported to Hubitat (when it's fully ready.)

I'm merging it, and can announce it after (probably tomorrow - I'm heading out now).

Thanks for putting it together.

**Comment by bspranger** [comment]
I was able to use button 0 with rule machine

**Comment by veeceeoh** [comment]
That's good news

**Pull request merged**
